version: '2.2'
services:

  django:
    build: .
    # Loading the app is defined here to allow for
    # autoreload on changes it is mounted on top of the
    # old copy that docker added when creating the image
    volumes:
      - '.:/usr/src/app'
    environment:
      - DEBUG=False
      - GEONODE_LB_HOST_IP=35.209.139.114
      - GEONODE_LB_PORT=80
      - SITEURL=http://35.209.139.114/
      - ALLOWED_HOSTS=['35.209.139.114', ]
      - GEOSERVER_PUBLIC_LOCATION=http://35.209.139.114/geoserver/
      - GEOSERVER_WEB_UI_LOCATION=http://35.209.139.114/geoserver/

  geoserver:
    environment:
      - GEONODE_LB_HOST_IP=35.209.139.114
      - GEONODE_LB_PORT=80
